VCS_REF:

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/me-webapp-bot
#    username: me-webapp-bot
#    password: s3cr3t
#
#  jpa:
#    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#      format_sql: false
#    show-sql: false

server:
  error:
    include-stacktrace: on_param

telegram:
  webApp:
    url: https://idiotic-spoon-123.surge.sh/
  bot:
    token: 
    name: MeWebAppBot